# This is AI generated code
"""Unit tests for the CLI's path-detection helpers and templates."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from epilatow_repo_shared import sp
from epilatow_repo_shared.cli import (
    _inject_shared_testpaths,
    _project_name,
    _read_locked_sha,
    _read_pinned_deps,
    _snapshot_vendored_paths,
    args_parser,
)


def test_inject_shared_testpaths_creates_section_from_scratch(
    tmp_path: Path,
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text('[project]\nname = "demo"\nversion = "0.0.1"\n')
    _inject_shared_testpaths(pyproject)
    body = pyproject.read_text()
    assert "[tool.pytest.ini_options]" in body
    assert '"_repo_shared/tests"' in body


def test_inject_shared_testpaths_appends_to_existing_testpaths(
    tmp_path: Path,
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        "[project]\n"
        'name = "demo"\n\n'
        "[tool.pytest.ini_options]\n"
        "# user comment that should survive\n"
        'testpaths = ["tests"]\n'
    )
    _inject_shared_testpaths(pyproject)
    body = pyproject.read_text()
    assert '"_repo_shared/tests"' in body
    assert '"tests"' in body
    assert "# user comment that should survive" in body


def test_inject_shared_testpaths_is_idempotent(tmp_path: Path) -> None:
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text('[project]\nname = "demo"\nversion = "0.0.1"\n')
    _inject_shared_testpaths(pyproject)
    first = pyproject.read_text()
    _inject_shared_testpaths(pyproject)
    second = pyproject.read_text()
    assert first == second
    # Only one occurrence -- the second call didn't re-append.
    assert second.count('"_repo_shared/tests"') == 1


def test_args_parser_init_defaults() -> None:
    parser = args_parser()
    args = parser.parse_args(["init"])
    assert args.command == "init"
    assert args.path is None


def test_args_parser_upgrade_with_sha() -> None:
    parser = args_parser()
    args = parser.parse_args(["upgrade", "abc1234"])
    assert args.command == "upgrade"
    assert args.sha == "abc1234"


def test_snapshot_empty_when_no_vendor_dir(tmp_path: Path) -> None:
    assert _snapshot_vendored_paths(tmp_path) == set()


def test_snapshot_includes_real_files_skips_symlinks(tmp_path: Path) -> None:
    vendor_dir = tmp_path / "_repo_shared" / "files"
    vendor_dir.mkdir(parents=True)
    real = vendor_dir / "CLAUDE.md"
    real.write_text("c")
    link = tmp_path / "_repo_shared" / "repo-shared"
    link.symlink_to(real)
    snap = _snapshot_vendored_paths(tmp_path)
    assert real in snap
    assert link not in snap


def test_read_pinned_deps_extracts_exact_pins() -> None:
    text = (
        "[project]\n"
        "dependencies = [\n"
        '    "mdformat==0.7.22",\n'
        '    "ruff==0.15.12",\n'
        '    "mypy==2.0.0",\n'
        "]\n"
    )
    assert _read_pinned_deps(text) == [
        ("mdformat", "0.7.22"),
        ("ruff", "0.15.12"),
        ("mypy", "2.0.0"),
    ]


def test_read_pinned_deps_skips_loose_constraints() -> None:
    text = (
        "[project]\n"
        "dependencies = [\n"
        '    "epilatow-repo-shared",\n'
        '    "pytest",\n'
        '    "ruff==0.15.12",\n'
        '    "mypy>=2.0",\n'
        "]\n"
    )
    assert _read_pinned_deps(text) == [("ruff", "0.15.12")]


def test_read_pinned_deps_stops_at_section_close() -> None:
    text = (
        "[project]\n"
        "dependencies = [\n"
        '    "ruff==0.15.12",\n'
        "]\n"
        "[other]\n"
        '"mypy==2.0.0"\n'
    )
    assert _read_pinned_deps(text) == [("ruff", "0.15.12")]


def test_args_parser_upgrade_tools_flags() -> None:
    parser = args_parser()
    args = parser.parse_args(["upgrade-tools", "--push", "--only", "ruff"])
    assert args.command == "upgrade-tools"
    assert args.push is True
    assert args.only == ["ruff"]


def _stub_uv_export(
    monkeypatch: pytest.MonkeyPatch,
    *,
    stdout: str,
    returncode: int = 0,
) -> list[list[str]]:
    """Capture argv passed to ``sp.run`` and return canned export output.

    Returns the captured argv list so a test can assert the invocation
    shape (e.g. that ``--format requirements-txt`` is being passed).
    """
    captured: list[list[str]] = []

    def fake(
        cmd: list[str], **_kwargs: object
    ) -> subprocess.CompletedProcess[str]:
        captured.append(list(cmd))
        return subprocess.CompletedProcess(
            args=cmd, returncode=returncode, stdout=stdout, stderr=""
        )

    monkeypatch.setattr(sp, "run", fake)
    return captured


_EXPORT_EXAMPLE = """\
# This file was autogenerated by uv via the following command:
#    uv export --format requirements-txt --no-hashes
-e .
epilatow-repo-shared @ git+https://github.com/epilatow/repo-shared@abc1234567def8901234567890abcdef12345678
    # via consumer-pkg
mdformat==0.7.22
    # via epilatow-repo-shared
"""


def test_read_locked_sha_extracts_from_uv_export(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "uv.lock").write_text("# stub -- real content lives in uv\n")
    captured = _stub_uv_export(monkeypatch, stdout=_EXPORT_EXAMPLE)

    sha = _read_locked_sha(tmp_path)
    assert sha == "abc1234567def8901234567890abcdef12345678"
    # Invocation shape: uv export with the stable requirements-txt format.
    assert captured == [
        [
            "uv",
            "export",
            "--format",
            "requirements-txt",
            "--no-hashes",
        ]
    ]


def test_read_locked_sha_returns_none_without_lockfile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # No uv.lock; ``_read_locked_sha`` should short-circuit without
    # shelling out (subprocess call is not stubbed -- if it ran the
    # test would fail with the real uv invocation).
    assert _read_locked_sha(tmp_path) is None


def test_read_locked_sha_returns_none_when_uv_export_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "uv.lock").write_text("# stub\n")
    _stub_uv_export(monkeypatch, stdout="", returncode=2)

    assert _read_locked_sha(tmp_path) is None


def test_read_locked_sha_returns_none_when_package_not_in_export(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "uv.lock").write_text("# stub\n")
    _stub_uv_export(
        monkeypatch,
        stdout=("-e .\nmdformat==0.7.22\nruff==0.15.12\n"),
    )

    assert _read_locked_sha(tmp_path) is None


def test_read_locked_sha_returns_none_for_non_git_source(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A consumer pinned to a wheel or local path has no git SHA to return."""
    (tmp_path / "uv.lock").write_text("# stub\n")
    _stub_uv_export(
        monkeypatch,
        stdout=(
            "epilatow-repo-shared @ file:///opt/wheels/epilatow_repo_shared"
            "-0.1.0-py3-none-any.whl\n"
        ),
    )

    assert _read_locked_sha(tmp_path) is None


def test_read_locked_sha_ignores_unrelated_git_pins(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A different git-pinned dep doesn't accidentally hijack the parse."""
    (tmp_path / "uv.lock").write_text("# stub\n")
    _stub_uv_export(
        monkeypatch,
        stdout=(
            "some-other-pkg @ git+https://example.invalid/foo"
            "@deadbeefdeadbeefdeadbeefdeadbeefdeadbeef\n"
            "epilatow-repo-shared @ git+https://github.com/epilatow/"
            "repo-shared@abc1234567def8901234567890abcdef12345678\n"
        ),
    )

    assert (
        _read_locked_sha(tmp_path)
        == "abc1234567def8901234567890abcdef12345678"
    )


def _git_init_with_initial_commit(repo: Path) -> None:
    subprocess.run(
        ["git", "init", "--quiet", "-b", "main", str(repo)],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        [
            "git",
            "-c",
            "user.email=test@example.invalid",
            "-c",
            "user.name=Test",
            "-C",
            str(repo),
            "commit",
            "--allow-empty",
            "--quiet",
            "-m",
            "init",
        ],
        check=True,
        capture_output=True,
    )


def test_project_name_in_main_checkout_is_repo_root_basename(
    tmp_path: Path,
) -> None:
    main = tmp_path / "my-project"
    main.mkdir()
    _git_init_with_initial_commit(main)
    assert _project_name(main) == "my-project"


def test_project_name_in_worktree_resolves_to_main_checkout_name(
    tmp_path: Path,
) -> None:
    """In a worktree, ``_project_name`` returns the main checkout's basename.

    Regression guard: ``Path.name`` of a worktree dir gives the
    worktree's local name (e.g. ``feature-branch``), not the
    project's. Without ``_project_name``, ``init`` would bake the
    worktree's directory name into ``[project].name`` of the freshly
    generated ``pyproject.toml`` -- a silently-wrong onboarding
    experience that only the maintainer would notice.
    """
    main = tmp_path / "my-project"
    main.mkdir()
    _git_init_with_initial_commit(main)
    wt = tmp_path / "my-project.wt" / "feature-branch"
    wt.parent.mkdir()
    subprocess.run(
        [
            "git",
            "-C",
            str(main),
            "worktree",
            "add",
            "--quiet",
            "-B",
            "feature-branch",
            str(wt),
        ],
        check=True,
        capture_output=True,
    )
    assert _project_name(wt) == "my-project"


def test_project_name_falls_back_to_basename_outside_git_repo(
    tmp_path: Path,
) -> None:
    """Pre-``git init`` consumer: no git answer available, basename it is."""
    plain = tmp_path / "plain-dir"
    plain.mkdir()
    assert _project_name(plain) == "plain-dir"
